---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    volumes:
      - jellyfin-config:/config
      - mediaserver:/media #optional
      - jellyfin-cache:/cache
    expose:
      - 8096
    ports:
      - "1900:1900/udp"
    restart: unless-stopped
    pull_policy: always
    networks:
      - networking
      - mediaserver
    environment:
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl=jellyfin.${DOMAINNAME_1}
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0 
    labels:
      - "org.label-schema.group=mediaserver"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.jellyfin-router.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-router.rule=Host(`jellyfin.$DOMAINNAME_1`)" # HostRegexp:jellyfin.${DOMAINNAME_1},{catchall:.*}" # Host(`jellyfin.$DOMAINNAME_1`)"
      # Middlewares
      #- "traefik.http.routers.homepage-router.middlewares=authentik-traefik@file"
      - "traefik.http.routers.jellyfin-router.middlewares=secure-headers-frame-jellyfin@file"
      # HTTP Services
      - "traefik.http.routers.jellyfin-router.service=jellyfin-service"
      - "traefik.http.services.jellyfin-service.loadbalancer.server.port=8096"
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin.svg
      - homepage.href=https://jellyfin.$DOMAINNAME_1
      - homepage.description=Jellyfin
      - homepage.showStats=true
      - homepage.widget.type=jellyfin
      - homepage.widget.url=https://jellyfin.$DOMAINNAME_1
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true # optional, defaults to false
      - homepage.widget.enableNowPlaying=true # optional, defaults to true
      - homepage.widget.enableUser=true # optional, defaults to false
      - homepage.widget.showEpisodeNumber=true # optional, defaults to false
      - homepage.widget.expandOneStreamToTwoRows=false # optional, defaults to true
        #- homepage.widget.fields=["field1","field2"] # optional

volumes:
  jellyfin-config:
    external: true
  jellyfin-cache:
    external: true
