services:
  komodo:
    container_name: komodo
    image: ghcr.io/moghtech/komodo-core:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    restart: unless-stopped
    pull_policy: always
    #depends_on:
    #  - mongo
    networks:
      - management
      - databases
      - networking
    #ports:
    #  - 9120:9120
    env_file: .env
    environment:
      KOMODO_DATABASE_ADDRESS: mongo:27017
      KOMODO_DATABASE_USERNAME: admin
      KOMODO_DATABASE_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    volumes:
      ## Store dated backups of the database - https://komo.do/docs/setup/backup
      - komodo-backups:/backups
      ## Store sync files on server
      # - /path/to/syncs:/syncs
      ## Optionally mount a custom core.config.toml
      - /komodo-config:/config
    ## Allows for systemd Periphery connection at 
    ## "https://host.docker.internal:8120"
    # extra_hosts:
    #   - host.docker.internal:host-gateway
    labels:                                                             
      - "komodo.skip:" # Prevent Komodo from stopping with StopAllContainers
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.komodo-router.entrypoints=websecure"
      - "traefik.http.routers.komodo-router.rule=Host(`komodo.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.komodo-router.middlewares=secure-headers@file"
      # HTTP Services
      - "traefik.http.routers.komodo-router.service=komodo-service"
      - "traefik.http.services.komodo-service.loadbalancer.server.port=9120"
      - homepage.group=Management
      - homepage.name=Komodo
      - homepage.icon=komodo.svg
      - homepage.href=https://komodo.$DOMAINNAME_1
      - homepage.description=Komodo
      - homepage.showStats=true

  ## Deploy Periphery container using this block,
  ## or deploy the Periphery binary with systemd using 
  ## https://github.com/moghtech/komodo/tree/main/scripts
  komodo-periphery:
    container_name: komodo-periphery
    image: ghcr.io/moghtech/komodo-periphery:${COMPOSE_KOMODO_IMAGE_TAG:-latest}
    restart: unless-stopped                                            
    pull_policy: always
    networks:
      - management
    env_file: .env
    volumes:
      ## Mount external docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      ## Allow Periphery to see processes outside of container
      - /proc:/proc
      ## Specify the Periphery agent root directory.
      ## Must be the same inside and outside the container,
      ## or docker will get confused. See https://github.com/moghtech/komodo/discussions/180.
      ## Default: /etc/komodo.
      - ${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}:${PERIPHERY_ROOT_DIRECTORY:-/etc/komodo}
    labels:                                                             
      komodo.skip: # Prevent Komodo from stopping with StopAllContainers

volumes:
  komodo-backups:
    external: true
  komodo-config:
    external: true
