services:
  teleport:
    container_name: teleport
    image: public.ecr.aws/gravitational/teleport-distroless:18.2.10
    pull_policy: always
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    networks:
      - networking
      - tools
    volumes:
      - teleport-data:/var/lib/teleport
      - teleport-config:/etc/teleport
    expose:
      - "3080"
      - "3025"
    environment:
      - TZ=${TZ}
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.teleport-router.entrypoints=websecure"
      - "traefik.http.routers.teleport-router.rule=HostRegexp(`teleport.$DOMAINNAME_1`) || Hostregexp(`{subdomain:[a-z0-9]+}.teleport.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.teleport-router.middlewares=secure-headers-https@file"
      - "traefik.http.routers.teleport-router.tls.options=tls-opts-no-snistrict@file"
      - "traefik.http.routers.teleport-router.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.teleport-router.tls.domains[0].main=teleport.$DOMAINNAME_1"
      - "traefik.http.routers.teleport-router.tls.domains[0].sans=*.teleport.$DOMAINNAME_1"
        #- "traefik.http.routers.teleport-router.middlewares=middlewares-buffer@file"
      # HTTP Services
      - "traefik.http.routers.teleport-router.service=teleport-service"
      - "traefik.http.services.teleport-service.loadbalancer.server.port=3080"
      - "traefik.http.services.teleport-service.loadbalancer.server.scheme=https"
      - homepage.group=Networking
      - homepage.name=Teleport
      - homepage.icon=teleport.svg
      - homepage.href=https://teleport.$DOMAINNAME_1
      - homepage.description=Teleport
      - homepage.showStats=true
        #- homepage.widget.type=emby
        #- homepage.widget.url=http://emby.home
        #- homepage.widget.key=yourembyapikeyhere
        #- homepage.widget.fields=["field1","field2"] # optiona

volumes:
  teleport-data:
    external: true
  teleport-config:
    external: true
