services:
  clamav:
    image: clamav/clamav:latest_base
    pull_policy: always
    container_name: clamav
    security_opt:
      - no-new-privileges:true
    restart: always
    networks:
      - security 
    environment:
      # - DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
      # - DOCKER_HOST: tcp://socket-proxy:2375
      - TZ=${TZ}
    volumes:
      - clamav-data:/var/lib/clamav
      - clamav-socket:/tmp
    labels:
      - "org.label-schema.group=security"
      - homepage.group=Security
      - homepage.name=Clamav
      - homepage.icon=clam-av.svg
        #- homepage.href=https://wazuh.$DOMAINNAME_1
      - homepage.description=Clamav
      - homepage.showStats=true
        #- homepage.widget.type=emby
        #- homepage.widget.url=http://emby.home
        #- homepage.widget.key=yourembyapikeyhere
        #- homepage.widget.fields=["field1","field2"] # optiona

volumes:
  clamav-data:
    external: true
  clamav-socket:
    external: true
