services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    container_name: open-webui
    pull_policy: always
    networks:
      - tools
      - networking
    #ports:
    #  - "3000:8080"
    volumes:
      - open-webui-data:/app/backend/data
    environment:
      - WEBUI_URL=open-webui.$DOMAINNAME_1
      - ADMIN_EMAIL=dockeradmin@$DOMAINNAME_1
    labels:
      - "org.label-schema.group=tools"
      - "traefik.enable=true"
      - "traefik.docker.network=networking"
      # HTTP Routers
      - "traefik.http.routers.open-webui-router.entrypoints=websecure"
      - "traefik.http.routers.open-webui-router.rule=Host(`open-webui.$DOMAINNAME_1`)" # HostRegexp:open-webui.${DOMAINNAME_1},{catchall:.*}" # Host(`open-webui.$DOMAINNAME_1`)"
      # Middlewares
      - "traefik.http.routers.open-webui-router.middlewares=secure-headers@file"
      #- "traefik.http.routers.open-webui-router.middlewares=authentik-traefik@file"
      # HTTP Services
      - "traefik.http.routers.open-webui-router.service=open-webui-service"
      - "traefik.http.services.open-webui-service.loadbalancer.server.port=8080"
      - homepage.group=AI & ML
      - homepage.name=Open WebUI
      - homepage.icon=open-webui.svg
      - homepage.href=https://open-webui.$DOMAINNAME_1
      - homepage.description=Open WebUI
      - homepage.showStats=true
        #- homepage.widget.type=emby
        #- homepage.widget.url=http://emby.home
        #- homepage.widget.key=yourembyapikeyhere
        #- homepage.widget.fields=["field1","field2"] # optional

volumes:
  open-webui-data:
    external: true
